export const GET_STUDENT_PENDING = "GET_STUDENT_PENDING";
export const GET_STUDENT_FULFILLED = "GET_STUDENT_FULFILLED";
export const GET_STUDENT_REJECTED = "GET_STUDENT_REJECTED";

export const DELETE_STUDENT_PENDING = "DELETE_STUDENT_PENDING";
export const DELETE_STUDENT_FULFILLED = "DELETE_STUDENT_FULFILLED";
export const DELETE_STUDENT_REJECTED = "DELETE_STUDENT_REJECTED";

export const ADD_STUDENT_PENDING = "ADD_STUDENT_PENDING";
export const ADD_STUDENT_FULFILLED = "ADD_STUDENT_FULFILLED";
export const ADD_STUDENT_REJECTED = "ADD_STUDENT_REJECTED";

export const UPDATE_STUDENT_PENDING = "UPDAE_STUDENT_PENDING";
export const UPDATE_STUDENT_FULFILLED = "UPDAE_STUDENT_FULFILLED";
export const UPDATE_STUDENT_REJECTED = "UPDAE_STUDENT_REJECTED";
